# Generated by Django 2.2.10 on 2020-12-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190527_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRegs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(blank=True, max_length=50, null=True)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('associatesNumber', models.IntegerField(blank=True, null=True)),
                ('employeesNumber', models.IntegerField(blank=True, null=True)),
                ('createdJobsNumber', models.IntegerField(blank=True, null=True)),
                ('fullAddress', models.CharField(blank=True, max_length=50, null=True)),
                ('wlaya', models.CharField(blank=True, max_length=100, null=True)),
                ('ownersEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('ownersLinkedin', models.URLField(blank=True, null=True)),
                ('contactEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobilePhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('mainPhoneNumber', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
