# Generated by Django 2.2.10 on 2020-12-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201206_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appregs',
            old_name='wlaya',
            new_name='wilaya',
        ),
    ]
