# Generated by Django 2.2.10 on 2020-12-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appregs',
            name='associatesNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
