# Generated by Django 2.2.10 on 2020-12-13 15:02

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20201213_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appregs',
            name='employeesNumber',
            field=models.IntegerField(blank=True, null=True, validators=[blog.models.validate_employees_Number]),
        ),
    ]
