# Generated by Django 2.2.10 on 2020-12-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_multistepformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='You_are',
            field=models.CharField(choices=[('Founder', 'Founder'), ('Co-founder', 'Co-founder')], max_length=225),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='prjfield',
            field=models.CharField(choices=[('Fintech', 'Fintech'), ('Cloud/Sass', 'Cloud/Sass'), ('Agritech (agriculture de précision)', 'Agritech (agriculture de précision)'), ('Economie circulaire (greentech)', 'Economie circulaire (greentech)'), ('E-learning/ Edtech', 'E-learning/ Edtech'), ('Govtech (e-administration)', 'Govtech (e-administration)'), ('IOT (internet des objets)', 'IOT (internet des objets)'), ('Legaltech', 'Legaltech'), ('Food tech', 'Food tech'), ('E-health (santé)', 'E-health (santé)'), ('Smart City', 'Smart City'), ('IOT (internet des objets)', 'IOT (internet des objets)'), ('Tourisme/voyage', 'Tourisme/voyage'), ('Energies renouvelables', 'Energies renouvelables'), ('Pharma', 'Pharma'), ('Education', 'Education'), ('Intelligence Artificielle', 'Intelligence Artificielle'), ('Réalité augmentée/virtuelle', 'Réalité augmentée/virtuelle'), ('E-services', 'E-services'), ('Economie sociale et solidaire.', 'Economie sociale et solidaire.'), ('Cybersecurity', 'Cybersecurity'), ('Electronique &amp; Composants', 'Electronique &amp; Composants'), ('C', 'C'), ('C', 'C'), ('C', 'C')], max_length=225),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='prjprgress',
            field=models.CharField(choices=[('Concept/Idea', 'Concept/Idea'), ('prototype in development', 'prototype in development'), ('prototype ready', 'prototype ready'), ('ready product', 'ready product')], max_length=225),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='wilaya',
            field=models.CharField(choices=[('أدرار', 'أدرار'), ('الشلف', 'الشلف'), ('الأغواط', 'الأغواط'), ('أم البواقي', 'أم البواقي'), ('باتنة', 'باتنة'), ('بجاية', 'بجاية'), ('بسكرة', 'بسكرة'), ('بشار', 'بشار'), ('البليدة', 'البليدة'), ('البويرة', 'البويرة'), ('تمنراست', 'تمنراست'), ('تبسة', 'تبسة'), ('تلمسان', 'تلمسان'), ('تيارت', 'تيارت'), ('تيزي وزو', 'تيزي وزو'), ('الجزائر', 'الجزائر'), ('الجلفة', 'الجلفة'), ('جيجل', 'جيجل'), ('سطيف', 'سطيف'), ('سعيدة', 'سعيدة'), ('سكيكدة', 'سكيكدة'), ('سيدي بلعباس', 'سيدي بلعباس'), ('عنابة', 'عنابة'), ('قالمة', 'قالمة'), ('قسنطينة', 'قسنطينة'), ('المدية', 'المدية'), ('مستغانم', 'مستغانم'), ('المسيلة', 'المسيلة'), ('معسكر', 'معسكر'), ('ورقلة', 'ورقلة'), ('وهران', 'وهران'), ('البيض', 'البيض'), ('إليزي', 'إليزي'), ('برج بوعريريج', 'برج بوعريريج'), ('بومرداس', 'بومرداس'), ('الطارف', 'الطارف'), ('تيندوف', 'تيندوف'), ('تيسمسيلت', 'تيسمسيلت'), ('وادي سوف', 'وادي سوف'), ('سوق أهراس', 'سوق أهراس'), ('تيبازة', 'تيبازة'), ('عين الدفلى', 'عين الدفلى'), ('النعامة', 'النعامة'), ('عين تيموشنت', 'عين تيموشنت'), ('غرداية', 'غرداية'), ('غليزان', 'غليزان')], max_length=225),
        ),
    ]
