# Generated by Django 2.2.10 on 2020-12-28 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201228_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='ytubeLink',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
