# Generated by Django 2.2.10 on 2020-12-28 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201228_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='You_are',
            field=models.CharField(max_length=225),
        ),
    ]
