# Generated by Django 2.2.10 on 2020-12-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201228_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='uploadfiles'),
        ),
    ]
