# Generated by Django 2.2.10 on 2020-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_multistepformmodel_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistepformmodel',
            name='document',
            field=models.FileField(upload_to='uploadfiles'),
        ),
    ]
