# Generated by Django 2.2.10 on 2020-12-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201228_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multistepformmodel',
            old_name='document',
            new_name='file',
        ),
    ]
