# Generated by Django 2.2.10 on 2020-12-29 04:32

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20201228_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistepformmodel',
            name='file_Br',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='multistepformmodel',
            name='file_CV',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='multistepformmodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=blog.models.user_directory_path),
        ),
    ]
